### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by TemKaSD** [Gameerr/SEtxt#1]
Привет Gameerr, во первых, выражаю тебе огромную благодарность за то, что ты делаешь. Уже не так много осталось людей, которые до сих пор что-то делают для длешки.

После установки хака ошибка на главной странцие: Fatal error: Call to undefined method SEtxt::construct() in /engine/classes/templates.class.php on line 49

Сделал по инструкции, проверил 2 раза.

**Comment by Gameerr** [comment]
Здравствуйте. Исправлено.
